---

- hosts: localhost
  connection: local
  tasks:
    - name: enable time machine support for network disks
      command: defaults write com.apple.systempreferences TMShowUnsupportedNetworkVolumes 1

    - name: disable richtext in textedit by default
      command: defaults write com.apple.TextEdit RichText 0

    - name: disable creating DS files
      command: defaults write com.apple.desktopservices DSDontWriteNetworkStores 1

    - name: install brew packages
      homebrew: name="{{ item }}" state=present
      with_items:
        - git
        - curl
        - wget
        - tmux
        - mc
        - ssh-copy-id
        - ctags
        - rbenv
        - ack
        - node
        - pwgen
        - pdf2htmlex
        - youtube-dl
        - icu4c
        - reattach-to-user-namespace
        - imagemagick
        - homebrew/versions/libpqxx3
        - sqlite
        - nmap
        - yarn
        - erlang
        - elixir
        - neovim/neovim/neovim
        - python3

    - name: neovim with python is intalled
      pip:
        name: neovim
        state: present
        executable: pip3

    - name: install xkbswitch
      get_url:
        url: https://github.com/myshov/xkbswitch-macosx/raw/master/bin/xkbswitch
        dest: /usr/local/bin/xkbswitch
        mode: 0755

    - name: create dotfiles dirs
      file: path="~/{{ item }}" state=directory
      with_items:
        - .ssh
        - .bundle
        - .config

    - name: install dotfiles
      copy: src="assets/{{ item }}" dest="~/{{ item }}" force=no
      with_items:
        - .aliases
        - .ansible.cfg
        - .bash_profile
        - .bundle/config
        - .ctags
        - .editorconfig
        - .eslintrc
        - .gemrc
        - .gitconfig
        - .gitignore_global
        - .rubocop.yml
        - .ssh/config
        - .sublime-settings
        - .tmux.conf
        - .vimrc

    - name: create nvim symlink
      file: src="/usr/local/bin/nvim" dest="/usr/local/bin/vim" state=link
      tags: nvim

    - name: create nvim data symlink
      file: src="~/.vim" dest="~/.config/nvim" state=link force=yes
      tags: nvim

    - name: create nvim config symlink
      file: src="~/.vimrc" dest="~/.config/nvim/init.vim" state=link force=yes
      tags: nvim

    - name: create sublime symlink
      file: src="/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" dest="/usr/local/bin/sublime" state=link force=yes
      tags: sublime
      ignore_errors: yes

    - name: install sublime config
      file:
        src: "~/.sublime-settings"
        dest: "~/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings"
        state: link
        force: yes
      tags: sublime
      ignore_errors: yes

    - name: install tmux resurrect plugin
      git: repo=https://github.com/tmux-plugins/tmux-resurrect dest="~/.tmux/plugins/tmux-resurrect"
      tags: tmux
