---

- hosts: localhost
  connection: local
  tasks:
    - name: install brew packages
      homebrew: name="{{ item }}" state=present
      with_items:
        - coreutils
        - git
        - curl
        - wget
        - tmux
        - mc
        - ssh-copy-id
        - ctags
        - rbenv
        - ack
        - node
        - pwgen
        - pdf2htmlex
        - youtube-dl
        - icu4c
        - reattach-to-user-namespace
        - sqlite
        - nmap
        - yarn
        - erlang
        - elixir
        - neovim/neovim/neovim
        - python3
        - kubernetes-cli
        - hiredis
        - p7zip
        - poppler
        - libxml2
        - ffmpeg
        - imagemagick@6
        - v8@3.15
        - libpqxx@3

    - name: cask packages are installed
      homebrew_cask: name="{{ item }}" state=present
      items:
        - tunnelblick
        - wkhtmltopdf
        - virtualbox
        - docker
        - kitematic
        - gpg-suite
        - google-cloud-sdk
        - minikube
        - java8

    - name: pip packages are installed
      pip:
        name: "{{ item }}"
        state: present
        executable: pip3
        extra_args: --user
      with_items:
        - neovim
        - awscli

    - name: node packages are installed
      npm: name="{{ item }}" state=present global=yes
      with_items:
        - eslint
        - eslint-plugin-react
        - babel-eslint

    - name: gems are installed
      gem: name="{{ item }}" state=present
      with_items:
        - bundler
        - bundle-audit
        - rubocop
        - neovim
        - tmuxinator
        - foreman
        - brakeman

    # configs

    - name: set config list
      set_fact:
        list:
          - .aliases
          - .ackrc
          - .ansible.cfg
          - .bash_profile
          - .bundle/config
          - .ctags
          - .editorconfig
          - .eslintrc
          - .gemrc
          - .gitconfig
          - .gitignore_global
          - .rubocop.yml
          - .sublime-settings
          - .sublime-keys
          - .sublime-packages
          - .tmux.conf
          - .config/nvim/init.vim
          - .vimrc
          - .private

    - name: mac settings are changed
      command: "defaults write {{ item }}"
      with_items:
        - "NSGlobalDomain ApplePressAndHoldEnabled 0"
        - "com.apple.systempreferences TMShowUnsupportedNetworkVolumes 1"
        - "com.apple.desktopservices DSDontWriteNetworkStores 1"
        - "com.apple.TextEdit RichText 0"

    - name: create config dirs
      file: path="~/{{ item | dirname }}" state=directory
      with_items: "{{ list }}"

    - name: create config links
      file:
        src: "{{ playbook_dir }}/assets/{{ item }}"
        dest: "~/{{ item }}"
        state: link
        force: yes
      with_items: "{{ list }}"

    # ssh

    - name: ssh dir is created
      file: path="~/.ssh" state=directory

    - name: ssh config link is created
      file:
        src: "~/.private/ssh_config"
        dest: "~/.ssh/config"
        state: link
        force: yes

    # sublime

    - name: create sublime symlink
      file:
        src: "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl"
        dest: "/usr/local/bin/sublime"
        state: link
      ignore_errors: yes

    - name: install sublime config
      file:
        src: "~/.sublime-settings"
        dest: "~/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings"
        state: link
        force: yes
      ignore_errors: yes

    - name: install sublime keys
      file:
        src: "~/.sublime-keys"
        dest: "~/Library/Application Support/Sublime Text 3/Packages/User/Default (OSX).sublime-keymap"
        state: link
        force: yes
      ignore_errors: yes

    - name: install sublime packages
      file:
        src: "~/.sublime-packages"
        dest: "~/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings"
        state: link
        force: yes
      ignore_errors: yes
