---

- hosts: localhost
  connection: local
  tasks:
    - name: set config list
      set_fact:
        list:
          - .aliases
          - .ackrc
          - .ansible.cfg
          - .bash_profile
          - .bundle/config
          - .ctags
          - .editorconfig
          - .eslintrc
          - .gemrc
          - .gitconfig
          - .gitignore_global
          - .rubocop.yml
          - .sublime-settings
          - .sublime-keys
          - .tmux.conf
          - .config/nvim/init.vim
          - .vimrc

    - name: create config dirs
      file: path="~/{{ item | dirname }}" state=directory
      with_items: "{{ list }}"

    - name: create config links
      file:
        src: "{{ playbook_dir }}/assets/{{ item }}"
        dest: "~/{{ item }}"
        state: link
        force: yes
      with_items: "{{ list }}"

    - name: ssh dir is created
      file: path="~/.ssh" state=directory

    - name: ssh config is created
      copy:
        src: "assets/.ssh/config"
        dest: "~/.ssh/config"
        force: no

    - name: install brew packages
      homebrew: name="{{ item }}" state=present
      with_items:
        - coreutils
        - git
        - curl
        - wget
        - tmux
        - mc
        - ssh-copy-id
        - ctags
        - rbenv
        - ack
        - node
        - pwgen
        - pdf2htmlex
        - youtube-dl
        - icu4c
        - reattach-to-user-namespace
        - imagemagick
        # - homebrew/versions/libpqxx3
        # - homebrew/versions/v8-315
        # - homebrew/dupes/apple-gcc42
        - sqlite
        - nmap
        - yarn
        - erlang
        - elixir
        - neovim/neovim/neovim
        - python3
        - kubernetes-cli

    - name: gems are installed
      gem: name="{{ item }}" state=present
      with_items:
        - bundler
        - rubocop
        - neovim
        - tmuxinator

    - name: node packages are installed
      npm: name=eslint state=present global=yes

    - name: pip3 packages are installed
      pip: name="{{ item }}" state=present executable=pip3
      with_items:
        - neovim

    - name: create sublime symlink
      file:
        src: "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl"
        dest: "/usr/local/bin/sublime"
        state: link
      ignore_errors: yes

    - name: install sublime config
      file:
        src: "~/.sublime-settings"
        dest: "~/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings"
        state: link
        force: yes
      ignore_errors: yes

    - name: install sublime keys
      file:
        src: "~/.sublime-keys"
        dest: "~/Library/Application Support/Sublime Text 3/Packages/User/Default (OSX).sublime-keymap"
        state: link
        force: yes
      ignore_errors: yes
