---

- hosts: localhost
  connection: local
  tasks:
    - name: install brew packages
      homebrew: name='{{ item }}' state=present
      with_items:
        - coreutils
        - git
        - curl
        - wget
        - tmux
        - mc
        - ssh-copy-id
        - icu4c
        - reattach-to-user-namespace
        - sqlite
        - neovim/neovim/neovim
        - python3
        - kubernetes-cli
        - libxml2
        - telnet
        - imagemagick@6
        - v8@3.15
        - zsh
        - tree

    - name: install oh-my-zsh
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: ~/.oh-my-zsh
        update: no

    - name: add HomeBrew custom repos
      homebrew_tap:
        name: homebrew/cask-versions

    - name: cask packages are installed
      homebrew_cask: name='{{ item }}' state=present
      with_items:
        - iterm2
        - font-fira-code
        - google-chrome
        - opera
        - slack
        - skype
        - discord-ptb
        - tunnelblick
        - virtualbox
        - vagrant
        - docker-edge
        - kitematic
        - google-cloud-sdk
        - kubernetes-helm
        - minikube
        - java8
        - flash-npapi
        - wireshark

    - name: pip packages are installed
      pip:
        name: '{{ item }}'
        state: present
        executable: pip3
        extra_args: --user
      with_items:
        - neovim
        - awscli
        - ansible-vault

    # configs

    - name: mac settings are changed
      command: 'defaults write {{ item }}'
      with_items:
        - 'NSGlobalDomain ApplePressAndHoldEnabled 0'
        - 'com.apple.systempreferences TMShowUnsupportedNetworkVolumes 1'
        - 'com.apple.desktopservices DSDontWriteNetworkStores 1'
        - 'com.apple.TextEdit RichText 0'
      changed_when: false

    - name: set config list
      set_fact:
        list:
          - .bundle/config
          - .oh-my-zsh/themes/gruz0.zsh-theme
          - .config/nvim/.keep
          - .ssh
          - .ansible.cfg
          - .bash_profile
          - .ctags
          - .editorconfig
          - .gemrc
          - .gitconfig
          - .gitignore_global
          - .tmux.conf
          - .vimrc
          - .zshrc

    - name: create config dirs
      file: path='~/{{ item | dirname }}' state=directory
      with_items: '{{ list }}'

    - name: create config links
      file:
        src: '{{ playbook_dir }}/assets/{{ item }}'
        dest: '~/{{ item }}'
        state: link
        force: yes
      with_items: '{{ list }}'

    - name: create NeoVim config symlink to Vim config
      file:
        src: '~/.vimrc'
        dest: '~/.config/nvim/init.vim'
        state: link
