---

- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: sublime link created
      file: src="/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" dest="/usr/local/bin/sublime" state=link force=yes

    - name: sublime config installed
      file: src="~/.sublime-settings" dest="~/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings" state=link force=yes

    - name: ssh config installed
      copy: src="ansible/ssh_config" dest="~/.ssh/config" force=no

    - name: time machines supports network disks
      command: defaults write com.apple.systempreferences TMShowUnsupportedNetworkVolumes 1

    - name: disable richtext in textedit
      command: defaults write com.apple.TextEdit RichText 0

    - name: force language for terminal
      command: defaults write -app Terminal AppleLanguages -array en
